name: Python Release

on:
  push:
    tags:
      - 'v*.*.*'
permissions:
  contents: write

jobs:
  build:
    name: Build Executables (Windows)
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'pip'

      - name: Upgrade setuptools, wheel, and install requirements
        run: |
          pip install --upgrade setuptools wheel pyinstaller~=5.13.2 && pip install -r requirements.txt

      - name: Build Pyinstaller
        shell: pwsh
        run: |
          pyinstaller --onefile --windowed --name "Bilibili-Order-Deleter" --version-file version_info.txt bilibili_order_deleter.py

      - name: Upload executable to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: ./dist/Bilibili-Order-Deleter.exe
          asset_name: Bilibili-Order-Deleter_windows_amd64_${{ github.ref_name }}.exe
          tag: ${{ github.ref }}
          overwrite: true